- name: Neo4j install preparation
  hosts: devops_server
  become: yes
  gather_facts: no
  tasks:
    - name: Chargement des variables d'environnment
      include_vars: "../{{ env }}.yml"

    - name: Remove VirtualEnv
      file:
        path: "{{ devops_path }}/venv"
        state: absent

    - name: Install python3-venv
      shell: apt-get -y install python3-venv

    - name: Create VirtualEnv
      shell: python3 -m venv "{{ devops_path }}/venv"

    - name: Install docker module in venv
      shell: "{{ devops_path }}/venv/bin/pip install docker"

    - name: Create artifactory group
      group:
        name: artifactory
        gid: 1030

    - name: Create artifactory user
      user:
        name: artifactory
        uid: 1030
        group: artifactory

    - name: Create deployment directory
      file:
        path: "{{ devops_tools.state_base_dir }}/jenkins"
        state: directory
        owner: artifactory
        group: artifactory
        recurse: yes

- name: Neo4j Configuration
  hosts: devops_server
  become: yes
  gather_facts: no
  tasks:
    - name: Remove Neo4j dir
      file:
        path: "{{ services_path }}/neo4j"
        state: absent
    - name: Create Neo4j dir
      file:
        path: "{{ services_path }}/neo4j"
        state: directory
        mode: '0755'
    - name: Copy docker-compose
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ services_path }}/neo4j/docker-compose.yml"

- name: Neo4j start
  hosts: devops_server
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ devops_path }}/venv/bin/python"
  tasks:
    - name: Restart Neo4j
      shell: docker-compose down; docker-compose up -d
      args:
        chdir: "{{ services_path }}/neo4j/"

