- name: ELK Configuration
  hosts: devops_server
  become: yes
  gather_facts: no
  tasks:
    - name: Remove ELK-Stack dir
      file:
        path: "{{ services_path }}/elk-stack"
        state: absent
    - name: Create ELK-stack dir
      file:
        path: "{{ services_path }}/elk-stack"
        state: directory
        mode: '0755'
    - name: Copy docker-compose
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ services_path }}/elk-stack/docker-compose.yml"

- name: ELK start
  hosts: devops_server
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ devops_path }}/venv/bin/python"
  tasks:
    - name: Restart ELK
      shell: docker-compose down; docker-compose up -d --remove-orphans
      args:
        chdir: "{{ services_path }}/elk-stack/"